// Curiosity Lab — Globe Explorer world data
// Country cards + label data. rank: 1 = biggest/best-known (shown first), 3 = reveal on zoom.
// capLat/capLng = capital city location (used for the "where" mini-map + capital dot).
// aliases cover the different names map datasets use, so clicks match the landmass.

export const COUNTRIES = [
  { name:"United States", flag:"🇺🇸", capital:"Washington, D.C.", capLat:38.90, capLng:-77.04, region:"North America", rank:1, cities:"New York, L.A., Chicago", aliases:["United States of America","USA"], fact:"Yellowstone Park sits on top of a giant sleeping supervolcano." },
  { name:"China", flag:"🇨🇳", capital:"Beijing", capLat:39.90, capLng:116.41, region:"East Asia", rank:1, cities:"Shanghai, Guangzhou", aliases:["People's Republic of China"], fact:"The Great Wall of China is more than 21,000 km long." },
  { name:"India", flag:"🇮🇳", capital:"New Delhi", capLat:28.61, capLng:77.21, region:"South Asia", rank:1, cities:"Mumbai, Bengaluru", aliases:[], fact:"India has the rainiest village on Earth — Mawsynram gets about 12 metres of rain a year." },
  { name:"Russia", flag:"🇷🇺", capital:"Moscow", capLat:55.75, capLng:37.62, region:"Eurasia", rank:1, cities:"St Petersburg", aliases:["Russian Federation"], fact:"Russia is so wide it stretches across 11 time zones." },
  { name:"Brazil", flag:"🇧🇷", capital:"Brasília", capLat:-15.79, capLng:-47.88, region:"South America", rank:1, cities:"São Paulo, Rio", aliases:[], fact:"The Amazon rainforest here makes about 1 in every 5 breaths of oxygen on Earth." },
  { name:"Canada", flag:"🇨🇦", capital:"Ottawa", capLat:45.42, capLng:-75.70, region:"North America", rank:1, cities:"Toronto, Vancouver", aliases:[], fact:"Canada has more lakes than the rest of the world combined." },
  { name:"Australia", flag:"🇦🇺", capital:"Canberra", capLat:-35.28, capLng:149.13, region:"Oceania", rank:1, cities:"Sydney, Melbourne", aliases:[], fact:"Australia is actually wider than the Moon!" },
  { name:"Japan", flag:"🇯🇵", capital:"Tokyo", capLat:35.68, capLng:139.69, region:"East Asia", rank:1, cities:"Osaka, Kyoto", aliases:[], fact:"Japan is made of over 6,800 islands — only about 430 have people living on them!" },
  { name:"Germany", flag:"🇩🇪", capital:"Berlin", capLat:52.52, capLng:13.40, region:"Western Europe", rank:1, cities:"Munich, Hamburg", aliases:[], fact:"Some German highways, the Autobahn, have stretches with no speed limit at all." },
  { name:"United Kingdom", flag:"🇬🇧", capital:"London", capLat:51.51, capLng:-0.13, region:"Northern Europe", rank:1, cities:"Manchester, Glasgow", aliases:["UK","England"], fact:"The London Underground is the oldest underground railway in the world." },
  { name:"France", flag:"🇫🇷", capital:"Paris", capLat:48.85, capLng:2.35, region:"Western Europe", rank:1, cities:"Marseille, Lyon", aliases:[], fact:"With its islands around the world, France touches 12 different time zones." },
  { name:"Mexico", flag:"🇲🇽", capital:"Mexico City", capLat:19.43, capLng:-99.13, region:"North America", rank:1, cities:"Guadalajara", aliases:[], fact:"Mexico City is slowly sinking — about 50 cm every year." },
  { name:"Indonesia", flag:"🇮🇩", capital:"Jakarta", capLat:-6.21, capLng:106.85, region:"Southeast Asia", rank:1, cities:"Surabaya, Bandung", aliases:[], fact:"Indonesia is built from more than 17,000 islands." },
  { name:"Egypt", flag:"🇪🇬", capital:"Cairo", capLat:30.04, capLng:31.24, region:"North Africa", rank:1, cities:"Alexandria, Giza", aliases:[], fact:"The Great Pyramid was the tallest building on Earth for 3,800 years." },
  { name:"South Africa", flag:"🇿🇦", capital:"Pretoria", capLat:-25.75, capLng:28.19, region:"Southern Africa", rank:1, cities:"Cape Town, Joburg", aliases:[], fact:"South Africa is the only country with three capital cities!" },
  { name:"Argentina", flag:"🇦🇷", capital:"Buenos Aires", capLat:-34.60, capLng:-58.38, region:"South America", rank:1, cities:"Córdoba, Rosario", aliases:[], fact:"Buenos Aires has the widest avenue in the world — 16 lanes across!" },
  { name:"Saudi Arabia", flag:"🇸🇦", capital:"Riyadh", capLat:24.71, capLng:46.68, region:"Middle East", rank:1, cities:"Jeddah, Mecca", aliases:[], fact:"Saudi Arabia has no rivers at all — not a single permanent one." },
  { name:"Italy", flag:"🇮🇹", capital:"Rome", capLat:41.90, capLng:12.50, region:"Southern Europe", rank:1, cities:"Milan, Naples", aliases:[], fact:"Rome has free drinking fountains on almost every street — over 2,500 of them." },
  { name:"Spain", flag:"🇪🇸", capital:"Madrid", capLat:40.42, capLng:-3.70, region:"Southern Europe", rank:1, cities:"Barcelona, Valencia", aliases:[], fact:"Spain throws 150,000 kg of tomatoes in one giant food fight each year!" },
  { name:"Nigeria", flag:"🇳🇬", capital:"Abuja", capLat:9.08, capLng:7.40, region:"West Africa", rank:1, cities:"Lagos, Kano", aliases:[], fact:"Nigeria is home to more than 500 different languages." },

  { name:"Turkey", flag:"🇹🇷", capital:"Ankara", capLat:39.93, capLng:32.87, region:"Eurasia", rank:2, cities:"Istanbul, Izmir", aliases:["Türkiye"], fact:"Istanbul is the only city in the world that sits on two continents at once." },
  { name:"Iran", flag:"🇮🇷", capital:"Tehran", capLat:35.69, capLng:51.39, region:"Middle East", rank:2, cities:"Mashhad, Isfahan", aliases:["Islamic Republic of Iran"], fact:"Iran has some of the oldest cities on Earth, lived in for over 7,000 years." },
  { name:"Thailand", flag:"🇹🇭", capital:"Bangkok", capLat:13.76, capLng:100.50, region:"Southeast Asia", rank:2, cities:"Chiang Mai", aliases:[], fact:"Bangkok's full ceremonial name is the longest city name on Earth." },
  { name:"Vietnam", flag:"🇻🇳", capital:"Hanoi", capLat:21.03, capLng:105.85, region:"Southeast Asia", rank:2, cities:"Ho Chi Minh City", aliases:["Viet Nam"], fact:"Vietnam has a cave so big it has its own jungle and clouds inside it." },
  { name:"Pakistan", flag:"🇵🇰", capital:"Islamabad", capLat:33.68, capLng:73.05, region:"South Asia", rank:2, cities:"Karachi, Lahore", aliases:[], fact:"Pakistan has the highest paved international road in the world." },
  { name:"Bangladesh", flag:"🇧🇩", capital:"Dhaka", capLat:23.81, capLng:90.41, region:"South Asia", rank:2, cities:"Chittagong", aliases:[], fact:"The world's largest mangrove forest, the Sundarbans, is home to tigers that swim." },
  { name:"Philippines", flag:"🇵🇭", capital:"Manila", capLat:14.60, capLng:120.98, region:"Southeast Asia", rank:2, cities:"Cebu, Davao", aliases:[], fact:"The Philippines is made of 7,641 islands." },
  { name:"South Korea", flag:"🇰🇷", capital:"Seoul", capLat:37.57, capLng:126.98, region:"East Asia", rank:2, cities:"Busan, Incheon", aliases:["Korea","Republic of Korea"], fact:"South Korea has the fastest internet on the planet." },
  { name:"Ukraine", flag:"🇺🇦", capital:"Kyiv", capLat:50.45, capLng:30.52, region:"Eastern Europe", rank:2, cities:"Kharkiv, Odesa", aliases:[], fact:"Ukraine has the deepest metro station in the world — 105 m underground." },
  { name:"Poland", flag:"🇵🇱", capital:"Warsaw", capLat:52.23, capLng:21.01, region:"Central Europe", rank:2, cities:"Kraków, Łódź", aliases:[], fact:"Poland has a forest where the trees mysteriously grow with bent trunks." },
  { name:"Netherlands", flag:"🇳🇱", capital:"Amsterdam", capLat:52.37, capLng:4.90, region:"Western Europe", rank:2, cities:"Rotterdam", aliases:[], fact:"A third of the Netherlands sits below sea level, kept dry by dikes." },
  { name:"Sweden", flag:"🇸🇪", capital:"Stockholm", capLat:59.33, capLng:18.06, region:"Northern Europe", rank:2, cities:"Gothenburg", aliases:[], fact:"Sweden has around 267,000 islands — most are completely empty." },
  { name:"Norway", flag:"🇳🇴", capital:"Oslo", capLat:59.91, capLng:10.75, region:"Northern Europe", rank:2, cities:"Bergen", aliases:[], fact:"In summer the Sun never fully sets here for weeks — the Midnight Sun!" },
  { name:"Finland", flag:"🇫🇮", capital:"Helsinki", capLat:60.17, capLng:24.94, region:"Northern Europe", rank:2, cities:"Tampere", aliases:[], fact:"Finland has 188,000 lakes — it's nicknamed the Land of a Thousand Lakes." },
  { name:"Denmark", flag:"🇩🇰", capital:"Copenhagen", capLat:55.68, capLng:12.57, region:"Northern Europe", rank:2, cities:"Aarhus", aliases:[], fact:"Denmark invented LEGO bricks — the name means 'play well'." },
  { name:"Switzerland", flag:"🇨🇭", capital:"Bern", capLat:46.95, capLng:7.45, region:"Western Europe", rank:2, cities:"Zürich, Geneva", aliases:[], fact:"Switzerland has enough nuclear shelters for every single person to hide." },
  { name:"Austria", flag:"🇦🇹", capital:"Vienna", capLat:48.21, capLng:16.37, region:"Central Europe", rank:2, cities:"Graz, Salzburg", aliases:[], fact:"The oldest zoo still running in the world is in Vienna." },
  { name:"Greece", flag:"🇬🇷", capital:"Athens", capLat:37.98, capLng:23.73, region:"Southern Europe", rank:2, cities:"Thessaloniki", aliases:[], fact:"Greece has around 6,000 islands — but people live on only 227 of them." },
  { name:"Portugal", flag:"🇵🇹", capital:"Lisbon", capLat:38.72, capLng:-9.14, region:"Southern Europe", rank:2, cities:"Porto", aliases:[], fact:"Lisbon is older than Rome — by about four centuries." },
  { name:"Ireland", flag:"🇮🇪", capital:"Dublin", capLat:53.35, capLng:-6.26, region:"Northern Europe", rank:2, cities:"Cork, Galway", aliases:[], fact:"Ireland has no wild snakes anywhere on the island." },
  { name:"Belgium", flag:"🇧🇪", capital:"Brussels", capLat:50.85, capLng:4.35, region:"Western Europe", rank:2, cities:"Antwerp", aliases:[], fact:"Belgium makes over 220,000 tonnes of chocolate every year." },
  { name:"Kenya", flag:"🇰🇪", capital:"Nairobi", capLat:-1.29, capLng:36.82, region:"East Africa", rank:2, cities:"Mombasa", aliases:[], fact:"Over a million wildebeest cross Kenya each year in the Great Migration." },
  { name:"Ethiopia", flag:"🇪🇹", capital:"Addis Ababa", capLat:9.03, capLng:38.74, region:"East Africa", rank:2, cities:"Dire Dawa", aliases:[], fact:"Ethiopia follows its own calendar — and it's about 7 years behind the rest of the world." },
  { name:"Tanzania", flag:"🇹🇿", capital:"Dodoma", capLat:-6.16, capLng:35.75, region:"East Africa", rank:2, cities:"Dar es Salaam", aliases:["United Republic of Tanzania"], fact:"Mount Kilimanjaro is the tallest free-standing mountain on Earth." },
  { name:"Morocco", flag:"🇲🇦", capital:"Rabat", capLat:34.02, capLng:-6.83, region:"North Africa", rank:2, cities:"Casablanca", aliases:[], fact:"Morocco has an entire city painted blue, and the edge of the Sahara." },
  { name:"Algeria", flag:"🇩🇿", capital:"Algiers", capLat:36.75, capLng:3.06, region:"North Africa", rank:2, cities:"Oran", aliases:[], fact:"Algeria is the biggest country in Africa — mostly Sahara Desert." },
  { name:"Colombia", flag:"🇨🇴", capital:"Bogotá", capLat:4.71, capLng:-74.07, region:"South America", rank:2, cities:"Medellín, Cali", aliases:[], fact:"Colombia has a river that turns five colours, like a liquid rainbow." },
  { name:"Peru", flag:"🇵🇪", capital:"Lima", capLat:-12.05, capLng:-77.04, region:"South America", rank:2, cities:"Cusco, Arequipa", aliases:[], fact:"Machu Picchu was built high in the Andes without wheels or iron tools." },
  { name:"Chile", flag:"🇨🇱", capital:"Santiago", capLat:-33.45, capLng:-70.67, region:"South America", rank:2, cities:"Valparaíso", aliases:[], fact:"The Atacama Desert here can go decades without a single drop of rain." },
  { name:"Venezuela", flag:"🇻🇪", capital:"Caracas", capLat:10.48, capLng:-66.90, region:"South America", rank:2, cities:"Maracaibo", aliases:[], fact:"Venezuela has the tallest waterfall on Earth — Angel Falls, 979 m." },
  { name:"New Zealand", flag:"🇳🇿", capital:"Wellington", capLat:-41.29, capLng:174.78, region:"Oceania", rank:2, cities:"Auckland", aliases:[], fact:"There are about 5 sheep for every single person in New Zealand." },
  { name:"Malaysia", flag:"🇲🇾", capital:"Kuala Lumpur", capLat:3.14, capLng:101.69, region:"Southeast Asia", rank:2, cities:"George Town", aliases:[], fact:"Malaysia has rainforests over 130 million years old — older than the Amazon." },
  { name:"Singapore", flag:"🇸🇬", capital:"Singapore", capLat:1.35, capLng:103.82, region:"Southeast Asia", rank:2, cities:"", aliases:[], fact:"Singapore has a giant garden with man-made 'supertrees' that glow at night." },
  { name:"United Arab Emirates", flag:"🇦🇪", short:"U.A.E.", capital:"Abu Dhabi", capLat:24.45, capLng:54.38, region:"Middle East", rank:1, cities:"Dubai", aliases:["UAE","Emirates"], fact:"Dubai has the tallest building on Earth — the Burj Khalifa, 828 m high." },
  { name:"Iraq", flag:"🇮🇶", capital:"Baghdad", capLat:33.31, capLng:44.36, region:"Middle East", rank:2, cities:"Basra, Mosul", aliases:[], fact:"Writing was invented here over 5,000 years ago, in ancient Mesopotamia." },
  { name:"Israel", flag:"🇮🇱", capital:"Jerusalem", capLat:31.78, capLng:35.22, region:"Middle East", rank:2, cities:"Tel Aviv", aliases:[], fact:"You can float effortlessly in the Dead Sea — it's so salty nothing sinks." },
  { name:"Kazakhstan", flag:"🇰🇿", capital:"Astana", capLat:51.17, capLng:71.43, region:"Central Asia", rank:2, cities:"Almaty", aliases:[], fact:"Kazakhstan is the biggest landlocked country in the world." },
  { name:"Cuba", flag:"🇨🇺", capital:"Havana", capLat:23.11, capLng:-82.37, region:"Caribbean", rank:2, cities:"Santiago de Cuba", aliases:[], fact:"Classic 1950s cars still cruise the streets of Havana every day." },
  { name:"Iceland", flag:"🇮🇸", capital:"Reykjavík", capLat:64.15, capLng:-21.94, region:"Northern Europe", rank:2, cities:"Akureyri", aliases:[], fact:"Iceland has zero mosquitoes — one of the only countries on Earth without them." },
  { name:"Mongolia", flag:"🇲🇳", capital:"Ulaanbaatar", capLat:47.89, capLng:106.91, region:"East Asia", rank:2, cities:"Erdenet", aliases:[], fact:"Mongolia has more horses than people." },

  { name:"Czechia", flag:"🇨🇿", capital:"Prague", capLat:50.08, capLng:14.44, region:"Central Europe", rank:3, cities:"Brno", aliases:["Czech Republic"], fact:"Prague Castle is the largest ancient castle in the world." },
  { name:"Hungary", flag:"🇭🇺", capital:"Budapest", capLat:47.50, capLng:19.04, region:"Central Europe", rank:3, cities:"Debrecen", aliases:[], fact:"Budapest has over 100 natural hot springs bubbling under the city." },
  { name:"Romania", flag:"🇷🇴", capital:"Bucharest", capLat:44.43, capLng:26.10, region:"Eastern Europe", rank:3, cities:"Cluj-Napoca", aliases:[], fact:"Romania is home to the spooky castle that inspired Dracula." },
  { name:"Serbia", flag:"🇷🇸", capital:"Belgrade", capLat:44.79, capLng:20.45, region:"Southeast Europe", rank:3, cities:"Novi Sad", aliases:["Republic of Serbia"], fact:"Belgrade is one of the oldest cities in Europe, fought over 115 times." },
  { name:"Croatia", flag:"🇭🇷", capital:"Zagreb", capLat:45.81, capLng:15.98, region:"Southeast Europe", rank:3, cities:"Split", aliases:[], fact:"The necktie was invented in Croatia." },
  { name:"Belarus", flag:"🇧🇾", capital:"Minsk", capLat:53.90, capLng:27.57, region:"Eastern Europe", rank:3, cities:"Gomel", aliases:[], fact:"Belarus has one of Europe's last patches of ancient wild forest, with bison." },
  { name:"Ghana", flag:"🇬🇭", capital:"Accra", capLat:5.60, capLng:-0.19, region:"West Africa", rank:3, cities:"Kumasi", aliases:[], fact:"Lake Volta in Ghana is the largest man-made lake on Earth by area." },
  { name:"Senegal", flag:"🇸🇳", capital:"Dakar", capLat:14.72, capLng:-17.47, region:"West Africa", rank:3, cities:"Touba", aliases:[], fact:"Senegal has a pink lake, coloured by tiny salt-loving algae." },
  { name:"Angola", flag:"🇦🇴", capital:"Luanda", capLat:-8.84, capLng:13.23, region:"Southern Africa", rank:3, cities:"Huambo", aliases:[], fact:"Angola has giant antelopes, the giant sable, found nowhere else." },
  { name:"Zimbabwe", flag:"🇿🇼", capital:"Harare", capLat:-17.83, capLng:31.05, region:"Southern Africa", rank:3, cities:"Bulawayo", aliases:[], fact:"Victoria Falls here is so wide its mist can be seen from 50 km away." },
  { name:"Uganda", flag:"🇺🇬", capital:"Kampala", capLat:0.35, capLng:32.58, region:"East Africa", rank:3, cities:"Gulu", aliases:[], fact:"Uganda is home to more than half of the world's mountain gorillas." },
  { name:"Sudan", flag:"🇸🇩", capital:"Khartoum", capLat:15.50, capLng:32.56, region:"North Africa", rank:3, cities:"Omdurman", aliases:[], fact:"Sudan has more pyramids than Egypt — over 200 of them!" },
  { name:"Libya", flag:"🇱🇾", capital:"Tripoli", capLat:32.89, capLng:13.19, region:"North Africa", rank:3, cities:"Benghazi", aliases:[], fact:"The hottest air temperature ever recorded was once claimed in Libya." },
  { name:"Tunisia", flag:"🇹🇳", capital:"Tunis", capLat:36.81, capLng:10.18, region:"North Africa", rank:3, cities:"Sfax", aliases:[], fact:"Parts of Star Wars were filmed in the Tunisian desert." },
  { name:"Jordan", flag:"🇯🇴", capital:"Amman", capLat:31.95, capLng:35.93, region:"Middle East", rank:3, cities:"Zarqa", aliases:[], fact:"The ancient city of Petra was carved straight into rose-red cliffs." },
  { name:"Lebanon", flag:"🇱🇧", capital:"Beirut", capLat:33.89, capLng:35.50, region:"Middle East", rank:3, cities:"Tripoli", aliases:[], fact:"Beirut has been destroyed and rebuilt seven times — it never gives up." },
  { name:"Qatar", flag:"🇶🇦", capital:"Doha", capLat:25.29, capLng:51.53, region:"Middle East", rank:3, cities:"Al Rayyan", aliases:[], fact:"Qatar is a desert peninsula, yet it hosted a whole football World Cup." },
  { name:"Kuwait", flag:"🇰🇼", capital:"Kuwait City", capLat:29.38, capLng:47.99, region:"Middle East", rank:3, cities:"", aliases:[], fact:"Kuwait can reach 54°C — one of the hottest places people live." },
  { name:"Oman", flag:"🇴🇲", capital:"Muscat", capLat:23.59, capLng:58.41, region:"Middle East", rank:3, cities:"Salalah", aliases:[], fact:"Oman grows frankincense, a treasure once worth more than gold." },
  { name:"Afghanistan", flag:"🇦🇫", capital:"Kabul", capLat:34.56, capLng:69.21, region:"South Asia", rank:3, cities:"Kandahar", aliases:[], fact:"Afghanistan sits on the ancient Silk Road that linked East and West." },
  { name:"Nepal", flag:"🇳🇵", capital:"Kathmandu", capLat:27.72, capLng:85.32, region:"South Asia", rank:3, cities:"Pokhara", aliases:[], fact:"Eight of the ten highest mountains on Earth are in Nepal, including Everest." },
  { name:"Sri Lanka", flag:"🇱🇰", capital:"Colombo", capLat:6.93, capLng:79.86, region:"South Asia", rank:3, cities:"Kandy", aliases:[], fact:"Sri Lanka is shaped like a teardrop and grows some of the world's best tea." },
  { name:"Myanmar", flag:"🇲🇲", capital:"Naypyidaw", capLat:19.76, capLng:96.08, region:"Southeast Asia", rank:3, cities:"Yangon", aliases:["Burma"], fact:"Myanmar has a plain dotted with over 2,000 ancient temples." },
  { name:"Cambodia", flag:"🇰🇭", capital:"Phnom Penh", capLat:11.56, capLng:104.92, region:"Southeast Asia", rank:3, cities:"Siem Reap", aliases:[], fact:"Angkor Wat in Cambodia is the largest religious monument in the world." },
  { name:"Laos", flag:"🇱🇦", capital:"Vientiane", capLat:17.97, capLng:102.63, region:"Southeast Asia", rank:3, cities:"Luang Prabang", aliases:["Lao PDR"], fact:"Laos has a mysterious valley scattered with giant ancient stone jars." },
  { name:"Uruguay", flag:"🇺🇾", capital:"Montevideo", capLat:-34.90, capLng:-56.16, region:"South America", rank:3, cities:"Salto", aliases:[], fact:"Uruguay was the very first country to host and win a football World Cup." },
  { name:"Paraguay", flag:"🇵🇾", capital:"Asunción", capLat:-25.30, capLng:-57.64, region:"South America", rank:3, cities:"Ciudad del Este", aliases:[], fact:"Paraguay has two official languages — Spanish and Guaraní." },
  { name:"Bolivia", flag:"🇧🇴", capital:"La Paz", capLat:-16.49, capLng:-68.15, region:"South America", rank:3, cities:"Santa Cruz", aliases:[], fact:"Bolivia's salt flat is so flat and shiny it works like a giant mirror." },
  { name:"Ecuador", flag:"🇪🇨", capital:"Quito", capLat:-0.18, capLng:-78.47, region:"South America", rank:3, cities:"Guayaquil", aliases:[], fact:"You can stand with one foot in each hemisphere on Ecuador's equator line." },
  { name:"Panama", flag:"🇵🇦", capital:"Panama City", capLat:8.98, capLng:-79.52, region:"Central America", rank:3, cities:"Colón", aliases:[], fact:"The Panama Canal lets ships take a shortcut between two oceans." },
  { name:"Costa Rica", flag:"🇨🇷", capital:"San José", capLat:9.93, capLng:-84.08, region:"Central America", rank:3, cities:"Alajuela", aliases:[], fact:"Tiny Costa Rica holds about 5% of all the species on Earth." },
  { name:"Guatemala", flag:"🇬🇹", capital:"Guatemala City", capLat:14.63, capLng:-90.51, region:"Central America", rank:3, cities:"Antigua", aliases:[], fact:"Chocolate was first made into a drink by the ancient Maya here." },
  { name:"Dominican Republic", flag:"🇩🇴", capital:"Santo Domingo", capLat:18.49, capLng:-69.93, region:"Caribbean", rank:3, cities:"Santiago", aliases:[], fact:"Santo Domingo was the first European city built in the Americas." },
  { name:"Jamaica", flag:"🇯🇲", capital:"Kingston", capLat:18.01, capLng:-76.79, region:"Caribbean", rank:3, cities:"Montego Bay", aliases:[], fact:"Jamaica has produced some of the fastest sprinters the world has ever seen." },
  { name:"Madagascar", flag:"🇲🇬", capital:"Antananarivo", capLat:-18.88, capLng:47.51, region:"East Africa", rank:3, cities:"Toamasina", aliases:[], fact:"9 in 10 of Madagascar's animals live nowhere else on Earth, like lemurs." },
  { name:"Cameroon", flag:"🇨🇲", capital:"Yaoundé", capLat:3.85, capLng:11.50, region:"Central Africa", rank:3, cities:"Douala", aliases:[], fact:"Cameroon is nicknamed 'Africa in miniature' for its many landscapes." },
  { name:"Ivory Coast", flag:"🇨🇮", capital:"Yamoussoukro", capLat:6.83, capLng:-5.29, region:"West Africa", rank:3, cities:"Abidjan", aliases:["Côte d'Ivoire","Cote d'Ivoire"], fact:"Ivory Coast grows more cocoa beans than any other country." },
  { name:"DR Congo", flag:"🇨🇩", capital:"Kinshasa", capLat:-4.32, capLng:15.31, region:"Central Africa", rank:3, cities:"Lubumbashi", aliases:["Democratic Republic of the Congo","Congo (Kinshasa)"], fact:"The Congo rainforest is the second-largest rainforest on Earth." },

  // ---- Africa: medium countries (rank 3) ----
  { name:"Mali", flag:"🇲🇱", capital:"Bamako", capLat:12.64, capLng:-8.00, region:"West Africa", rank:3, cities:"Timbuktu", aliases:[], fact:"Timbuktu in Mali was once one of the world's greatest centres of learning." },
  { name:"Niger", flag:"🇳🇪", capital:"Niamey", capLat:13.51, capLng:2.11, region:"West Africa", rank:3, cities:"Zinder", aliases:[], fact:"Niger is named after the great Niger River that curves right through it." },
  { name:"Chad", flag:"🇹🇩", capital:"N'Djamena", capLat:12.11, capLng:15.05, region:"Central Africa", rank:3, cities:"Moundou", aliases:[], fact:"Lake Chad was once one of the largest lakes in all of Africa." },
  { name:"Mauritania", flag:"🇲🇷", capital:"Nouakchott", capLat:18.08, capLng:-15.98, region:"West Africa", rank:3, cities:"Nouadhibou", aliases:[], fact:"Mauritania has a giant 'Eye of the Sahara' you can spot from space." },
  { name:"Mozambique", flag:"🇲🇿", capital:"Maputo", capLat:-25.97, capLng:32.58, region:"Southern Africa", rank:3, cities:"Beira", aliases:[], fact:"Mozambique is the only one-word country name to use all five vowels." },
  { name:"Zambia", flag:"🇿🇲", capital:"Lusaka", capLat:-15.42, capLng:28.28, region:"Southern Africa", rank:3, cities:"Kitwe", aliases:[], fact:"Zambia shares the mighty Victoria Falls with neighbouring Zimbabwe." },
  { name:"Botswana", flag:"🇧🇼", capital:"Gaborone", capLat:-24.65, capLng:25.91, region:"Southern Africa", rank:3, cities:"Francistown", aliases:[], fact:"Botswana is home to one of the largest elephant populations on Earth." },
  { name:"Namibia", flag:"🇳🇦", capital:"Windhoek", capLat:-22.56, capLng:17.08, region:"Southern Africa", rank:3, cities:"Swakopmund", aliases:[], fact:"Namibia has some of the tallest sand dunes anywhere in the world." },
  { name:"Somalia", flag:"🇸🇴", capital:"Mogadishu", capLat:2.04, capLng:45.34, region:"East Africa", rank:3, cities:"Hargeisa", aliases:[], fact:"Somalia has the longest coastline on mainland Africa." },
  { name:"South Sudan", flag:"🇸🇸", capital:"Juba", capLat:4.85, capLng:31.58, region:"East Africa", rank:3, cities:"Malakal", aliases:["S. Sudan"], fact:"South Sudan is the youngest country in the world — born in 2011." },
  { name:"Central African Republic", flag:"🇨🇫", short:"C.A.R.", capital:"Bangui", capLat:4.39, capLng:18.55, region:"Central Africa", rank:3, cities:"Bimbo", aliases:["Central African Rep."], fact:"Its rainforests shelter forest elephants and lowland gorillas." },
  { name:"Gabon", flag:"🇬🇦", capital:"Libreville", capLat:0.42, capLng:9.47, region:"Central Africa", rank:3, cities:"Port-Gentil", aliases:[], fact:"Almost 90% of Gabon is covered in thick rainforest." },
  { name:"Republic of the Congo", flag:"🇨🇬", short:"Congo", capital:"Brazzaville", capLat:-4.27, capLng:15.28, region:"Central Africa", rank:3, cities:"Pointe-Noire", aliases:["Congo","Congo-Brazzaville","Congo (Brazzaville)"], fact:"Brazzaville and Kinshasa are the closest capital cities on Earth — just a river apart." },
  { name:"Malawi", flag:"🇲🇼", capital:"Lilongwe", capLat:-13.96, capLng:33.77, region:"East Africa", rank:3, cities:"Blantyre", aliases:[], fact:"Lake Malawi has more kinds of fish than any other lake on Earth." },
  { name:"Eritrea", flag:"🇪🇷", capital:"Asmara", capLat:15.34, capLng:38.93, region:"East Africa", rank:3, cities:"Keren", aliases:[], fact:"Asmara is full of dreamy 1930s Art Deco buildings." },

  // ---- Africa: small countries (rank 4, reveal at high zoom) ----
  { name:"Burkina Faso", flag:"🇧🇫", capital:"Ouagadougou", capLat:12.37, capLng:-1.53, region:"West Africa", rank:4, cities:"Bobo-Dioulasso", aliases:[], fact:"Burkina Faso hosts the biggest film festival in Africa." },
  { name:"Benin", flag:"🇧🇯", capital:"Porto-Novo", capLat:6.50, capLng:2.60, region:"West Africa", rank:4, cities:"Cotonou", aliases:[], fact:"Benin has an entire village built on stilts above a lake." },
  { name:"Togo", flag:"🇹🇬", capital:"Lomé", capLat:6.13, capLng:1.22, region:"West Africa", rank:4, cities:"Sokodé", aliases:[], fact:"Togo is one of the narrowest countries in all of Africa." },
  { name:"Guinea", flag:"🇬🇳", capital:"Conakry", capLat:9.64, capLng:-13.58, region:"West Africa", rank:4, cities:"Nzérékoré", aliases:[], fact:"Guinea is called the 'water tower of West Africa' for its many rivers." },
  { name:"Sierra Leone", flag:"🇸🇱", capital:"Freetown", capLat:8.48, capLng:-13.23, region:"West Africa", rank:4, cities:"Bo", aliases:[], fact:"Sierra Leone has one of the largest natural harbours in the world." },
  { name:"Liberia", flag:"🇱🇷", capital:"Monrovia", capLat:6.30, capLng:-10.80, region:"West Africa", rank:4, cities:"Gbarnga", aliases:[], fact:"Liberia is the oldest republic in Africa." },
  { name:"Rwanda", flag:"🇷🇼", capital:"Kigali", capLat:-1.95, capLng:30.06, region:"East Africa", rank:4, cities:"Butare", aliases:[], fact:"Rwanda is known as the 'Land of a Thousand Hills'." },
  { name:"Burundi", flag:"🇧🇮", capital:"Gitega", capLat:-3.43, capLng:29.93, region:"East Africa", rank:4, cities:"Bujumbura", aliases:[], fact:"Burundi sits beside Lake Tanganyika, one of the deepest lakes on Earth." },
  { name:"Equatorial Guinea", flag:"🇬🇶", short:"Eq. Guinea", capital:"Malabo", capLat:3.75, capLng:8.78, region:"Central Africa", rank:4, cities:"Bata", aliases:[], fact:"Its capital sits on a volcanic island out in the sea." },
  { name:"Lesotho", flag:"🇱🇸", capital:"Maseru", capLat:-29.31, capLng:27.48, region:"Southern Africa", rank:4, cities:"Teyateyaneng", aliases:[], fact:"Lesotho is circled entirely by South Africa and sits high in the mountains." },
  { name:"Eswatini", flag:"🇸🇿", capital:"Mbabane", capLat:-26.32, capLng:31.13, region:"Southern Africa", rank:4, cities:"Manzini", aliases:["Swaziland"], fact:"Eswatini is one of the world's last kingdoms still ruled by a king." },
  { name:"Gambia", flag:"🇬🇲", capital:"Banjul", capLat:13.45, capLng:-16.58, region:"West Africa", rank:4, cities:"Serekunda", aliases:["The Gambia"], fact:"The Gambia is the smallest country on mainland Africa." },
  { name:"Guinea-Bissau", flag:"🇬🇼", capital:"Bissau", capLat:11.86, capLng:-15.58, region:"West Africa", rank:4, cities:"Bafatá", aliases:["Guinea Bissau"], fact:"Guinea-Bissau is made up of a maze of tropical islands." },
  { name:"Djibouti", flag:"🇩🇯", capital:"Djibouti", capLat:11.59, capLng:43.15, region:"East Africa", rank:4, cities:"Ali Sabieh", aliases:[], fact:"Djibouti has a lake so salty it's crusted in white salt." },

  // ---- Europe & Caucasus fills (rank 4) ----
  { name:"Bulgaria", flag:"🇧🇬", capital:"Sofia", capLat:42.70, capLng:23.32, region:"Southeast Europe", rank:4, cities:"Plovdiv", aliases:[], fact:"Bulgaria is one of the world's biggest growers of roses for perfume." },
  { name:"Slovakia", flag:"🇸🇰", capital:"Bratislava", capLat:48.15, capLng:17.11, region:"Central Europe", rank:4, cities:"Košice", aliases:[], fact:"Slovakia has more castles and chateaux per person than any country." },
  { name:"Slovenia", flag:"🇸🇮", capital:"Ljubljana", capLat:46.06, capLng:14.51, region:"Central Europe", rank:4, cities:"Maribor", aliases:[], fact:"More than half of Slovenia is covered in forest." },
  { name:"Lithuania", flag:"🇱🇹", capital:"Vilnius", capLat:54.69, capLng:25.28, region:"Northern Europe", rank:4, cities:"Kaunas", aliases:[], fact:"Lithuania is famous for amber — ancient tree resin from the Baltic Sea." },
  { name:"Latvia", flag:"🇱🇻", capital:"Riga", capLat:56.95, capLng:24.11, region:"Northern Europe", rank:4, cities:"Daugavpils", aliases:[], fact:"Riga is famous for its fairy-tale Art Nouveau buildings." },
  { name:"Estonia", flag:"🇪🇪", capital:"Tallinn", capLat:59.44, capLng:24.75, region:"Northern Europe", rank:4, cities:"Tartu", aliases:[], fact:"Estonia was one of the first countries where you could vote online." },
  { name:"Bosnia & Herzegovina", flag:"🇧🇦", short:"Bosnia", capital:"Sarajevo", capLat:43.86, capLng:18.41, region:"Southeast Europe", rank:4, cities:"Mostar", aliases:["Bosnia and Herzegovina","Bosnia and Herz.","Bosnia"], fact:"Mostar's famous arched bridge has stood and been rebuilt over centuries." },
  { name:"Albania", flag:"🇦🇱", capital:"Tirana", capLat:41.33, capLng:19.82, region:"Southeast Europe", rank:4, cities:"Durrës", aliases:[], fact:"Albania has more than 170,000 old concrete bunkers dotted across it." },
  { name:"North Macedonia", flag:"🇲🇰", short:"N. Macedonia", capital:"Skopje", capLat:41.99, capLng:21.43, region:"Southeast Europe", rank:4, cities:"Bitola", aliases:["Macedonia"], fact:"Lake Ohrid here is one of the oldest and deepest lakes in Europe." },
  { name:"Moldova", flag:"🇲🇩", capital:"Chișinău", capLat:47.01, capLng:28.86, region:"Eastern Europe", rank:4, cities:"Tiraspol", aliases:[], fact:"Moldova has the largest wine cellar in the world." },
  { name:"Georgia", flag:"🇬🇪", capital:"Tbilisi", capLat:41.72, capLng:44.78, region:"Caucasus", rank:4, cities:"Batumi", aliases:[], fact:"People have been making wine in Georgia for around 8,000 years." },
  { name:"Armenia", flag:"🇦🇲", capital:"Yerevan", capLat:40.18, capLng:44.51, region:"Caucasus", rank:4, cities:"Gyumri", aliases:[], fact:"Armenia was the first country to make Christianity its national religion." },
  { name:"Azerbaijan", flag:"🇦🇿", capital:"Baku", capLat:40.41, capLng:49.87, region:"Caucasus", rank:4, cities:"Ganja", aliases:[], fact:"Azerbaijan has hillsides of natural flames that never stop burning." },

  // ---- Central Asia, Middle East & Americas fills (rank 4) ----
  { name:"Uzbekistan", flag:"🇺🇿", capital:"Tashkent", capLat:41.31, capLng:69.24, region:"Central Asia", rank:4, cities:"Samarkand", aliases:[], fact:"Uzbekistan is one of only two countries you must cross twice to reach the sea." },
  { name:"Turkmenistan", flag:"🇹🇲", capital:"Ashgabat", capLat:37.96, capLng:58.33, region:"Central Asia", rank:4, cities:"Türkmenabat", aliases:[], fact:"A fiery crater here, the 'Door to Hell', has burned for over 50 years." },
  { name:"Kyrgyzstan", flag:"🇰🇬", capital:"Bishkek", capLat:42.87, capLng:74.59, region:"Central Asia", rank:4, cities:"Osh", aliases:[], fact:"Kyrgyzstan is almost all mountains, with a huge lake that never freezes." },
  { name:"Tajikistan", flag:"🇹🇯", capital:"Dushanbe", capLat:38.56, capLng:68.79, region:"Central Asia", rank:4, cities:"Khujand", aliases:[], fact:"Over half of Tajikistan lies above 3,000 metres high." },
  { name:"Syria", flag:"🇸🇾", capital:"Damascus", capLat:33.51, capLng:36.29, region:"Middle East", rank:4, cities:"Aleppo", aliases:[], fact:"Damascus is one of the oldest cities people have lived in non-stop." },
  { name:"Yemen", flag:"🇾🇪", capital:"Sana'a", capLat:15.37, capLng:44.19, region:"Middle East", rank:4, cities:"Aden", aliases:[], fact:"Yemen has mud 'tower houses' that are like ancient skyscrapers." },
  { name:"Honduras", flag:"🇭🇳", capital:"Tegucigalpa", capLat:14.07, capLng:-87.19, region:"Central America", rank:4, cities:"San Pedro Sula", aliases:[], fact:"Legend says it once rained fish from the sky in Honduras." },
  { name:"Nicaragua", flag:"🇳🇮", capital:"Managua", capLat:12.11, capLng:-86.24, region:"Central America", rank:4, cities:"León", aliases:[], fact:"Nicaragua is dotted with volcanoes — one island has two side by side." },
  { name:"El Salvador", flag:"🇸🇻", capital:"San Salvador", capLat:13.69, capLng:-89.22, region:"Central America", rank:4, cities:"Santa Ana", aliases:[], fact:"El Salvador is nicknamed the 'Land of Volcanoes'." },
  { name:"Haiti", flag:"🇭🇹", capital:"Port-au-Prince", capLat:18.59, capLng:-72.31, region:"Caribbean", rank:4, cities:"Cap-Haïtien", aliases:[], fact:"Haiti was the first country in the world founded by freed enslaved people." },
  { name:"Papua New Guinea", flag:"🇵🇬", short:"P.N.G.", capital:"Port Moresby", capLat:-9.44, capLng:147.18, region:"Oceania", rank:4, cities:"Lae", aliases:[], fact:"Papua New Guinea has over 800 languages — the most of any country." }
];

// Big non-capital cities — used only as map labels at higher zoom, not clickable cards.
export const MEGACITIES = [
  { name:"New York", lat:40.71, lng:-74.01, rank:1 },
  { name:"Shanghai", lat:31.23, lng:121.47, rank:1 },
  { name:"Mumbai", lat:19.08, lng:72.88, rank:1 },
  { name:"São Paulo", lat:-23.55, lng:-46.63, rank:1 },
  { name:"Los Angeles", lat:34.05, lng:-118.24, rank:1 },
  { name:"Istanbul", lat:41.01, lng:28.98, rank:1 },
  { name:"Karachi", lat:24.86, lng:67.01, rank:2 },
  { name:"Sydney", lat:-33.87, lng:151.21, rank:1 },
  { name:"Hong Kong", lat:22.32, lng:114.17, rank:1 },
  { name:"Rio de Janeiro", lat:-22.91, lng:-43.17, rank:2 },
  { name:"Toronto", lat:43.65, lng:-79.38, rank:2 },
  { name:"Cape Town", lat:-33.92, lng:18.42, rank:2 },
  { name:"Dubai", lat:25.20, lng:55.27, rank:1 },
  { name:"Barcelona", lat:41.39, lng:2.17, rank:2 },
  { name:"Guangzhou", lat:23.13, lng:113.26, rank:2 },
  { name:"Chennai", lat:13.08, lng:80.27, rank:2 },
  { name:"Kolkata", lat:22.57, lng:88.36, rank:2 },
  { name:"Bengaluru", lat:12.97, lng:77.59, rank:2 },
  { name:"Lagos", lat:6.52, lng:3.38, rank:2 },
  { name:"Osaka", lat:34.69, lng:135.50, rank:2 },
  { name:"Chicago", lat:41.88, lng:-87.63, rank:2 },
  { name:"Melbourne", lat:-37.81, lng:144.96, rank:2 },
  { name:"Munich", lat:48.14, lng:11.58, rank:3 },
  { name:"Milan", lat:45.46, lng:9.19, rank:3 },
  { name:"Vancouver", lat:49.28, lng:-123.12, rank:3 },
  { name:"Casablanca", lat:33.57, lng:-7.59, rank:3 },
  { name:"Ho Chi Minh City", lat:10.82, lng:106.63, rank:3 },
  { name:"Busan", lat:35.18, lng:129.08, rank:3 },
  { name:"Saint Petersburg", lat:59.93, lng:30.34, rank:3 }
];

// Secondary well-known cities — the deepest label tier, revealed only at high zoom. Labels only, not clickable.
export const MINORCITIES = [
  { name:"Kyoto", lat:35.01, lng:135.77 },
  { name:"Yokohama", lat:35.44, lng:139.64 },
  { name:"Nagoya", lat:35.18, lng:136.91 },
  { name:"Fukuoka", lat:33.59, lng:130.40 },
  { name:"Shenzhen", lat:22.54, lng:114.06 },
  { name:"Chengdu", lat:30.57, lng:104.07 },
  { name:"Xi'an", lat:34.34, lng:108.94 },
  { name:"Pune", lat:18.52, lng:73.86 },
  { name:"Ahmedabad", lat:23.02, lng:72.57 },
  { name:"Jaipur", lat:26.91, lng:75.79 },
  { name:"Surabaya", lat:-7.25, lng:112.75 },
  { name:"Bandung", lat:-6.91, lng:107.61 },
  { name:"Cebu", lat:10.32, lng:123.90 },
  { name:"Chiang Mai", lat:18.79, lng:98.99 },
  { name:"Da Nang", lat:16.05, lng:108.20 },
  { name:"Brisbane", lat:-27.47, lng:153.03 },
  { name:"Perth", lat:-31.95, lng:115.86 },
  { name:"Auckland", lat:-36.85, lng:174.76 },
  { name:"Venice", lat:45.44, lng:12.32 },
  { name:"Florence", lat:43.77, lng:11.26 },
  { name:"Naples", lat:40.85, lng:14.27 },
  { name:"Marseille", lat:43.30, lng:5.37 },
  { name:"Lyon", lat:45.76, lng:4.84 },
  { name:"Hamburg", lat:53.55, lng:9.99 },
  { name:"Frankfurt", lat:50.11, lng:8.68 },
  { name:"Cologne", lat:50.94, lng:6.96 },
  { name:"Porto", lat:41.15, lng:-8.61 },
  { name:"Seville", lat:37.39, lng:-5.99 },
  { name:"Valencia", lat:39.47, lng:-0.38 },
  { name:"Manchester", lat:53.48, lng:-2.24 },
  { name:"Edinburgh", lat:55.95, lng:-3.19 },
  { name:"Kraków", lat:50.06, lng:19.94 },
  { name:"Gothenburg", lat:57.71, lng:11.97 },
  { name:"Bergen", lat:60.39, lng:5.32 },
  { name:"Bilbao", lat:43.26, lng:-2.93 },
  { name:"Bologna", lat:44.49, lng:11.34 },
  { name:"Geneva", lat:46.20, lng:6.14 },
  { name:"Zurich", lat:47.37, lng:8.54 },
  { name:"Rotterdam", lat:51.92, lng:4.48 },
  { name:"Antwerp", lat:51.22, lng:4.40 },
  { name:"Thessaloniki", lat:40.64, lng:22.94 },
  { name:"Antalya", lat:36.90, lng:30.70 },
  { name:"Boston", lat:42.36, lng:-71.06 },
  { name:"San Francisco", lat:37.77, lng:-122.42 },
  { name:"Seattle", lat:47.61, lng:-122.33 },
  { name:"Miami", lat:25.76, lng:-80.19 },
  { name:"Houston", lat:29.76, lng:-95.37 },
  { name:"Montreal", lat:45.50, lng:-73.57 },
  { name:"Guadalajara", lat:20.67, lng:-103.35 },
  { name:"Medellín", lat:6.24, lng:-75.57 },
  { name:"Cusco", lat:-13.53, lng:-71.97 },
  { name:"Salvador", lat:-12.97, lng:-38.50 },
  { name:"Alexandria", lat:31.20, lng:29.92 },
  { name:"Marrakesh", lat:31.63, lng:-7.99 },
  { name:"Mombasa", lat:-4.04, lng:39.67 },
  { name:"Tel Aviv", lat:32.08, lng:34.78 },
  { name:"Johannesburg", lat:-26.20, lng:28.05 },
  { name:"Durban", lat:-29.86, lng:31.02 },
  { name:"Dar es Salaam", lat:-6.79, lng:39.21 },
  { name:"Abidjan", lat:5.36, lng:-4.01 },
  { name:"Kano", lat:12.00, lng:8.52 },
  { name:"Samarkand", lat:39.65, lng:66.97 },
  { name:"Aleppo", lat:36.20, lng:37.16 }
].map(c=>({ ...c, rank:4 }));

// IANA time zone for each country (keyed by COUNTRIES name) — used for the live
// "what time is it there?" clock so it stays correct with DST and half-hour offsets.
export const TZ = {
  "United States":"America/New_York", "China":"Asia/Shanghai", "India":"Asia/Kolkata",
  "Russia":"Europe/Moscow", "Brazil":"America/Sao_Paulo", "Canada":"America/Toronto",
  "Australia":"Australia/Sydney", "Japan":"Asia/Tokyo", "Germany":"Europe/Berlin",
  "United Kingdom":"Europe/London", "France":"Europe/Paris", "Mexico":"America/Mexico_City",
  "Indonesia":"Asia/Jakarta", "Egypt":"Africa/Cairo", "South Africa":"Africa/Johannesburg",
  "Argentina":"America/Argentina/Buenos_Aires", "Saudi Arabia":"Asia/Riyadh", "Italy":"Europe/Rome",
  "Spain":"Europe/Madrid", "Nigeria":"Africa/Lagos", "Turkey":"Europe/Istanbul",
  "Iran":"Asia/Tehran", "Thailand":"Asia/Bangkok", "Vietnam":"Asia/Ho_Chi_Minh",
  "Pakistan":"Asia/Karachi", "Bangladesh":"Asia/Dhaka", "Philippines":"Asia/Manila",
  "South Korea":"Asia/Seoul", "Ukraine":"Europe/Kyiv", "Poland":"Europe/Warsaw",
  "Netherlands":"Europe/Amsterdam", "Sweden":"Europe/Stockholm", "Norway":"Europe/Oslo",
  "Finland":"Europe/Helsinki", "Denmark":"Europe/Copenhagen", "Switzerland":"Europe/Zurich",
  "Austria":"Europe/Vienna", "Greece":"Europe/Athens", "Portugal":"Europe/Lisbon",
  "Ireland":"Europe/Dublin", "Belgium":"Europe/Brussels", "Kenya":"Africa/Nairobi",
  "Ethiopia":"Africa/Addis_Ababa", "Tanzania":"Africa/Dar_es_Salaam", "Morocco":"Africa/Casablanca",
  "Algeria":"Africa/Algiers", "Colombia":"America/Bogota", "Peru":"America/Lima",
  "Chile":"America/Santiago", "Venezuela":"America/Caracas", "New Zealand":"Pacific/Auckland",
  "Malaysia":"Asia/Kuala_Lumpur", "Singapore":"Asia/Singapore", "United Arab Emirates":"Asia/Dubai",
  "Iraq":"Asia/Baghdad", "Israel":"Asia/Jerusalem", "Kazakhstan":"Asia/Almaty",
  "Cuba":"America/Havana", "Iceland":"Atlantic/Reykjavik", "Mongolia":"Asia/Ulaanbaatar",
  "Czechia":"Europe/Prague", "Hungary":"Europe/Budapest", "Romania":"Europe/Bucharest",
  "Serbia":"Europe/Belgrade", "Croatia":"Europe/Zagreb", "Belarus":"Europe/Minsk",
  "Ghana":"Africa/Accra", "Senegal":"Africa/Dakar", "Angola":"Africa/Luanda",
  "Zimbabwe":"Africa/Harare", "Uganda":"Africa/Kampala", "Sudan":"Africa/Khartoum",
  "Libya":"Africa/Tripoli", "Tunisia":"Africa/Tunis", "Jordan":"Asia/Amman",
  "Lebanon":"Asia/Beirut", "Qatar":"Asia/Qatar", "Kuwait":"Asia/Kuwait",
  "Oman":"Asia/Muscat", "Afghanistan":"Asia/Kabul", "Nepal":"Asia/Kathmandu",
  "Sri Lanka":"Asia/Colombo", "Myanmar":"Asia/Yangon", "Cambodia":"Asia/Phnom_Penh",
  "Laos":"Asia/Vientiane", "Uruguay":"America/Montevideo", "Paraguay":"America/Asuncion",
  "Bolivia":"America/La_Paz", "Ecuador":"America/Guayaquil", "Panama":"America/Panama",
  "Costa Rica":"America/Costa_Rica", "Guatemala":"America/Guatemala", "Dominican Republic":"America/Santo_Domingo",
  "Jamaica":"America/Jamaica", "Madagascar":"Indian/Antananarivo", "Cameroon":"Africa/Douala",
  "Ivory Coast":"Africa/Abidjan", "DR Congo":"Africa/Kinshasa", "Mali":"Africa/Bamako",
  "Niger":"Africa/Niamey", "Chad":"Africa/Ndjamena", "Mauritania":"Africa/Nouakchott",
  "Mozambique":"Africa/Maputo", "Zambia":"Africa/Lusaka", "Botswana":"Africa/Gaborone",
  "Namibia":"Africa/Windhoek", "Somalia":"Africa/Mogadishu", "South Sudan":"Africa/Juba",
  "Central African Republic":"Africa/Bangui", "Gabon":"Africa/Libreville", "Republic of the Congo":"Africa/Brazzaville",
  "Malawi":"Africa/Blantyre", "Eritrea":"Africa/Asmara", "Burkina Faso":"Africa/Ouagadougou",
  "Benin":"Africa/Porto-Novo", "Togo":"Africa/Lome", "Guinea":"Africa/Conakry",
  "Sierra Leone":"Africa/Freetown", "Liberia":"Africa/Monrovia", "Rwanda":"Africa/Kigali",
  "Burundi":"Africa/Bujumbura", "Equatorial Guinea":"Africa/Malabo", "Lesotho":"Africa/Maseru",
  "Eswatini":"Africa/Mbabane", "Gambia":"Africa/Banjul", "Guinea-Bissau":"Africa/Bissau",
  "Djibouti":"Africa/Djibouti", "Bulgaria":"Europe/Sofia", "Slovakia":"Europe/Bratislava",
  "Slovenia":"Europe/Ljubljana", "Lithuania":"Europe/Vilnius", "Latvia":"Europe/Riga",
  "Estonia":"Europe/Tallinn", "Bosnia & Herzegovina":"Europe/Sarajevo", "Albania":"Europe/Tirane",
  "North Macedonia":"Europe/Skopje", "Moldova":"Europe/Chisinau", "Georgia":"Asia/Tbilisi",
  "Armenia":"Asia/Yerevan", "Azerbaijan":"Asia/Baku", "Uzbekistan":"Asia/Tashkent",
  "Turkmenistan":"Asia/Ashgabat", "Kyrgyzstan":"Asia/Bishkek", "Tajikistan":"Asia/Dushanbe",
  "Syria":"Asia/Damascus", "Yemen":"Asia/Aden", "Honduras":"America/Tegucigalpa",
  "Nicaragua":"America/Managua", "El Salvador":"America/El_Salvador", "Haiti":"America/Port-au-Prince",
  "Papua New Guinea":"Pacific/Port_Moresby"
};
